apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
spec:
  template:
    spec:
      containers:
        - command:
            - argocd-server
            - --staticassets
            - /shared/app
            - --insecure
          name: argocd-server
