---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: $(workshop_namespace)-argocd-secret
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    resourceNames:
      - argocd-initial-admin-secret
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: $(workshop_namespace)-argocd-server
rules:
  - apiGroups:
      - ""
    resources:
      - services
    resourceNames:
      - argocd-server
    verbs:
      - get
---
apiVersion: kpack.io/v1alpha1
kind: ClusterStore
metadata:
  name: $(workshop_namespace)-store
spec:
  sources:
    - image: paketobuildpacks/builder:base
---
apiVersion: kpack.io/v1alpha1
kind: ClusterStack
metadata:
  name: $(workshop_namespace)-stack
spec:
  id: "io.buildpacks.stacks.bionic"
  buildImage:
    image: "paketobuildpacks/build:base-cnb"
  runImage:
    image: "paketobuildpacks/run:base-cnb"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: $(workshop_namespace)-kpack-ro
rules:
  - apiGroups:
      - kpack.io
    resources:
      - clusterbuilders
      - clusterstacks
      - clusterstores
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: $(workshop_namespace)-kpack-rw
rules:
  - apiGroups:
      - kpack.io
    resources:
      - builders
      - builds
      - images
      - sourceresolvers
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: $(workshop_namespace)-argo-rw
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - applications
      - appprojects
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
