apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

configMapGenerator:
  - name: argocd-cm
    behavior: merge
    literals:
      - accounts.image-updater=apiKey
      - kustomize.buildOptions=--load_restrictor LoadRestrictionsNone
  - name: argocd-rbac-cm
    behavior: merge
    literals:
      - policy.default=role:readonly
    files:
      - policy.csv
  - name: argocd-image-updater-config
    behavior: merge
    literals:
      - log.level=debug
