apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: springone-tour-lab-workshop-3
spec:
  title: SpringOne Tour 2021 Workshop 3
  description: SpringOne Tour 2021 Workshop 3
  vendor: eduk8s.io
  difficulty: beginner
  duration: 120m
  url: https://github.com/springone-tour-2021/lab-workshop-3
  content:
    #image: quay.io/eduk8s/lab-markdown-sample:master
    #files: github.com/eduk8s/lab-markdown-sample
    files: github.com/springone-tour-2021/lab-workshop-3
  session:
    namespaces:
      budget: small
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
      editor:
        enabled: true
