apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: lab-workshop-3
spec:
  title: SpringOne Tour 2021 Workshop 3
  description: SpringOne Tour 2021 Workshop 3
  vendor: eduk8s.io
  difficulty: beginner
  duration: 120m
  url: https://github.com/springone-tour-2021/lab-workshop-3
  content:
    image: quay.io/eduk8s/jdk11-environment:latest
    files: github.com/springone-tour-2021/lab-workshop-3?ref=develop-ivan
  session:
    config:
      vars:
        - name: GITHUB_ORG
          value: undefined
    namespaces:
      budget: large
      secondary:
        - name: $(session_namespace)-dev
        - name: $(session_namespace)-prod
        - name: $(session_namespace)-kpack
        - name: $(session_namespace)-argocd
#    resources:
#      memory: 1.7Gi
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
      editor:
        enabled: true
      registry:
        enabled: true
      docker:
        enabled: true
    objects:
      - apiVersion: rbac.authorization.k8s.io/v1
        kind: Role
        metadata:
          name: kpack-user
        rules:
          - apiGroups:
              - kpack.io
            resources:
              - clusterbuilders
              - clusterstacks
              - clusterstores
              - builders
              - builds
              - images
              - sourceresolvers
            verbs:
              - get
              - list
              - watch
              - create
              - delete
              - patch
              - update
      - apiVersion: rbac.authorization.k8s.io/v1
        kind: RoleBinding
        metadata:
          name: kpack-user
        roleRef:
          apiGroup: rbac.authorization.k8s.io
          kind: Role
          name: kpack-user
        subjects:
          - kind: ServiceAccount
#              namespace: $(workshop_namespace)
            namespace: $(session_namespace)-kpack
            name: $(service_account)
      - apiVersion: rbac.authorization.k8s.io/v1
        kind: Role
        metadata:
          name: argocd-user
        rules:
          - apiGroups:
              - argoproj.io
            resources:
              - applications
              - appprojects
            verbs:
              - get
              - list
              - watch
              - create
              - delete
              - patch
              - update
      - apiVersion: rbac.authorization.k8s.io/v1
        kind: RoleBinding
        metadata:
          name: argocd-user
        roleRef:
          apiGroup: rbac.authorization.k8s.io
          kind: Role
          name: argocd-user
        subjects:
          - kind: ServiceAccount
            #              namespace: $(workshop_namespace)
            namespace: $(session_namespace)-argocd
            name: $(service_account)
