apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: lab-workshop-3
spec:
  title: SpringOne Tour 2021 Workshop 3
  description: SpringOne Tour 2021 Workshop 3
  vendor: eduk8s.io
  difficulty: beginner
  duration: 120m
  url: https://github.com/springone-tour-2021/lab-workshop-3
  content:
    image: quay.io/eduk8s/jdk11-environment:latest
    files: github.com/springone-tour-2021/lab-workshop-3?ref=main
  session:
    namespaces:
      budget: large
      secondary:
        - name: $(session_namespace)-dev
        - name: $(session_namespace)-prod
    #    resources:
    #      memory: 1.7Gi
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
      editor:
        enabled: true
      registry:
        enabled: true
      docker:
        enabled: true
    objects:
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: $(session_namespace)-kpack-user-ro
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: $(workshop_namespace)-kpack-ro
      subjects:
        - kind: ServiceAccount
          namespace: $(workshop_namespace)
          name: $(service_account)
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: $(session_namespace)-kpack-user-rw
        namespace: $(session_namespace)
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: $(workshop_namespace)-kpack-rw
      subjects:
        - kind: ServiceAccount
          namespace: $(workshop_namespace)
          name: $(service_account)
  environment:
    objects:
    - apiVersion: kpack.io/v1alpha1
      kind: ClusterStore
      metadata:
        name: $(workshop_namespace)-store
      spec:
        sources:
          - image: paketobuildpacks/builder:base
    - apiVersion: kpack.io/v1alpha1
      kind: ClusterStack
      metadata:
        name: $(workshop_namespace)-stack
      spec:
        id: "io.buildpacks.stacks.bionic"
        buildImage:
          image: "paketobuildpacks/build:base-cnb"
        runImage:
          image: "paketobuildpacks/run:base-cnb"
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      metadata:
        name: $(workshop_namespace)-kpack-ro
      rules:
        - apiGroups:
            - kpack.io
          resources:
            - clusterbuilders
            - clusterstacks
            - clusterstores
          verbs:
            - get
            - list
            - watch
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      metadata:
        name: $(workshop_namespace)-kpack-rw
      rules:
        - apiGroups:
            - kpack.io
          resources:
            - builders
            - builds
            - images
            - sourceresolvers
          verbs:
            - get
            - list
            - watch
            - create
            - delete
            - patch
            - update