apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# This needs to be applied per session, so this would reapply all resources tens of times...bases:
resources:
  - ../../base

configMapGenerator:
  - name: argocd-cm
    behavior: merge
    literals:
      - kustomize.buildOptions=--load_restrictor LoadRestrictionsNone
#      - accounts.image-updater=apiKey
      - accounts.eduk8s-labs-w01-s001-argocd-user=apiKey, login
      - accounts.eduk8s-labs-w01-s002-argocd-user=apiKey, login
      - accounts.eduk8s-labs-w01-s003-argocd-user=apiKey, login
      - accounts.eduk8s-labs-w01-s004-argocd-user=apiKey, login
      - accounts.eduk8s-labs-w01-s005-argocd-user=apiKey, login
      - accounts.eduk8s-labs-w02-s001-argocd-user=apiKey, login
      - accounts.eduk8s-labs-w02-s002-argocd-user=apiKey, login
      - accounts.eduk8s-labs-w03-s001-argocd-user=apiKey, login
      - accounts.eduk8s-labs-w03-s002-argocd-user=apiKey, login
      - accounts.eduk8s-labs-w04-s001-argocd-user=apiKey, login
      - accounts.eduk8s-labs-w04-s002-argocd-user=apiKey, login
      - accounts.eduk8s-labs-w05-s001-argocd-user=apiKey, login
      - accounts.eduk8s-labs-w05-s002-argocd-user=apiKey, login
  - name: argocd-rbac-cm
    behavior: merge
    literals:
      - policy.default=role:readonly
    files:
      - policy.csv
  - name: argocd-image-updater-config
    behavior: merge
    literals:
      - log.level=debug
