#!/bin/bash

# This script is run after ~/.bash_profile
# For more information, see:
# https://docs.edukates.io/en/latest/workshop-content/workshop-runtime.html?#terminal-user-shell-environment

# Customize the prompt to make it easier on the eyes
export PS1_OLD="$PS1"
export PS1="\n\[\033[33m\]\w\$ \[\033[0m\]"

# The following works in combination with workshop/setup.d/httpie.sh
alias http="/home/eduk8s/bin/httpie/bin/http"