apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - argocd-server-external-callback-http-ingress.yaml
  - argocd-server-grpc-ingress.yaml
  - argocd-server-http-ingress.yaml

configMapGenerator:
  - name: argocd-cm
    behavior: merge
    literals:
      - kustomize.buildOptions=--load_restrictor LoadRestrictionsNone
      - accounts.image-updater=apiKey
  - name: argocd-rbac-cm
    behavior: merge
    literals:
      - policy.default=role:readonly
    files:
      - policy.csv
  - name: argocd-image-updater-config
    behavior: merge
    literals:
      - log.level=debug

patches:
  - ./argocd-server-deployment-patch.yaml
  - ./argocd-server-service-patch.yaml